name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 13, flags: ['-O3 -march=native']}
          - {compiler: intel, version: '2025.0', flags: ['-O3 -xhost']}
          - {compiler: intel-classic, version: '2021.10', flags: ['-O3 -xhost']}
          - {compiler: nvidia-hpc, version: '25.1', flags: ['-Mpreprocess -Ofast']}
        include:
          - os: ubuntu-latest
            toolchain: {compiler: gcc, version: 12, flags: ['-O3 -march=native']}
        exclude:
          - os: macos-latest
            toolchain: {compiler: intel, version: '2025.0'}
          - os: macos-latest
            toolchain: {compiler: nvidia-hpc, version: '25.1'}
          - os: windows-latest
            toolchain: {compiler: nvidia-hpc, version: '25.1'}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - uses: fortran-lang/setup-fortran@main
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Setup Fortran Package Manager
        uses: fortran-lang/setup-fpm@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Fortran on MacOS
        if: contains( matrix.os, 'macos')
        run: |
          brew reinstall gcc@13
          ln -s /usr/local/lib/gcc/13/libgfortran.5.dylib /usr/local/lib/
          ln -s /usr/local/lib/gcc/13/libquadmath.0.dylib /usr/local/lib/

      - run: |
          fpm test --compiler ${{ env.FC }} --c-compiler ${{ env.CC }} --cxx-compiler ${{ env.CXX }} --flag "${{ join(matrix.toolchain.flags, ' ') }}"
    #      ${{ env.FC }} ... # environment vars FC, CC, and CXX are set
    #      ${{ steps.setup-fortran.outputs.fc }} ... # outputs work too
