name: ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest,  compiler: gfortran,  flags: '-O3 -march=native -mtune=native -flto -ffat-lto-objects'}
          - {os: ubuntu-latest,  compiler: ifx,       flags: '-O3 -xhost'}
          - {os: ubuntu-latest,  compiler: flang-new, flags: '-O3'}
          - {os: ubuntu-latest,  compiler: lfortran,  flags: '-O3',           fpm-version: '0.12.0'}
          - {os: ubuntu-latest,  compiler: nvfortran, flags: '-Mpreprocess -Ofast -Minline'}
          - {os: macos-latest,   compiler: gfortran,  flags: '-O3 -mcpu=native -flto -ffat-lto-objects'}
          - {os: windows-latest, compiler: gfortran,  flags: '-O3 -march=native -mtune=native -flto -ffat-lto-objects'}
          - {os: windows-latest, compiler: ifx,       flags: '-O3',           fpm-version: '0.12.0'}
          - {os: windows-latest, compiler: flang-new, flags: '-O3'}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fortran compiler and fpm
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          fpm-version: ${{ matrix.fpm-version }}

      - run: |
          fpm test --compiler ${{ env.FPM_FC }} --c-compiler ${{ env.FPM_CC }} --cxx-compiler ${{ env.FPM_CXX }} --flag "${{ matrix.flags }}"
