name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 13, flags: ['-O3 -march=native -mtune=native -flto']}
          - {compiler: intel, version: '2025.2', flags: ['-O3 -xhost -flto']}
          - {compiler: intel-classic, version: '2021.10', flags: ['-O3 -xhost -ipo']}
          - {compiler: nvidia-hpc, version: '25.5', flags: ['-Mpreprocess -Ofast -Minline']}
        include:
          - os: ubuntu-latest
            toolchain: {compiler: gcc, version: 12, flags: ['-O3 -march=native -mtune=native -flto']}
        exclude:
          - os: macos-latest
            toolchain: {compiler: intel, version: '2025.2'}
          - os: macos-latest
            toolchain: {compiler: nvidia-hpc, version: '25.5'}
          - os: windows-latest
            toolchain: {compiler: nvidia-hpc, version: '25.5'}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - uses: fortran-lang/setup-fortran@main
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Setup Fortran Package Manager
        uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          fpm test --compiler ${{ env.FC }} --c-compiler ${{ env.CC }} --cxx-compiler ${{ env.CXX }} --flag "${{ join(matrix.toolchain.flags, ' ') }}"
    #      ${{ env.FC }} ... # environment vars FC, CC, and CXX are set
    #      ${{ steps.setup-fortran.outputs.fc }} ... # outputs work too
